name: ⚙️ CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@main

      - name: (env) setup node v${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: (env) prepare
        run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

      - name: Install
        run: pnpm install

      - name: Compiles
        run: pnpm run build

      - name: Test
        if: false
        run: pnpm run test

      - name: Check Types
        run: pnpm run typecheck
